<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-08T23:30:39Z" name="Suite" finished-at="2023-02-08T23:31:19Z" duration-ms="39614">
    <groups>
      <group name="smoke">
        <method signature="LoginTest.enterCorrectEmailandPasswordTest()[pri:2, instance:com.qa.tests.LoginTest@7690781]" name="enterCorrectEmailandPasswordTest" class="com.qa.tests.LoginTest"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2023-02-08T23:30:39Z" name="Test" finished-at="2023-02-08T23:31:19Z" duration-ms="39614">
      <class name="com.qa.tests.NotificationTest">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.qa.tests.NotificationTest@77eca502]" started-at="2023-02-08T23:30:40Z" name="beforeMethod" finished-at="2023-02-08T23:30:52Z" duration-ms="12705" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="clickNotificationLinkTest()[pri:0, instance:com.qa.tests.NotificationTest@77eca502]" started-at="2023-02-08T23:30:52Z" name="clickNotificationLinkTest" finished-at="2023-02-08T23:31:00Z" duration-ms="7925" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickNotificationLinkTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.qa.tests.NotificationTest@77eca502]" started-at="2023-02-08T23:31:00Z" name="afterMethod" finished-at="2023-02-08T23:31:01Z" duration-ms="760" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.qa.tests.NotificationTest@77eca502]" started-at="2023-02-08T23:31:01Z" name="beforeMethod" finished-at="2023-02-08T23:31:11Z" duration-ms="9622" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="verifyNotificationTextDispalyTest()[pri:0, instance:com.qa.tests.NotificationTest@77eca502]" started-at="2023-02-08T23:31:11Z" name="verifyNotificationTextDispalyTest" finished-at="2023-02-08T23:31:18Z" duration-ms="7800" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.qa.tests.NotificationTest.verifyNotificationTextDispalyTest(NotificationTest.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNotificationTextDispalyTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.qa.tests.NotificationTest@77eca502]" started-at="2023-02-08T23:31:18Z" name="afterMethod" finished-at="2023-02-08T23:31:19Z" duration-ms="745" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.qa.tests.NotificationTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
